/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2u1HjESkaos
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Navbar from "./Navbar"

export function Homepage() {
  return (
    <div className="flex flex-col min-h-[100dvh] dark:bg-neutral-900">
      Example Home Page
    </div>
  )
}
